flag for compiling or installing binaries of build dependencies

diff --git a/pacmoon b/pacmoon
--- a/pacmoon
+++ b/pacmoon
@@ -76,7 +76,8 @@ pacman_output_field() {
 dbPath=$(pacman_output_field -v DB)
 typeset -A split_pkgs
 typeset -A requested_pkgs
-typeset -a install_list
+typeset -a install_pkgs
+typeset -A makedep_pkgs
 typeset -a cyclic_deps
 
 is_dep() {
@@ -121,6 +122,45 @@ build_pkg() {
     [[ $+keep_temp = 0 ]] && rm -rf "$pmoonHome/tmp/$name"
     popd
 }
+
+resolve_name() {
+    local name=$1
+    local name_v=$2
+
+    local pq_fmt="%1 %s %n %v"
+    typeset -a pkgData
+    pkgData=( $(package-query -Qf $pq_fmt --query-type provides $name_v || \
+                package-query -Qif $pq_fmt $name_v || \
+                package-query -Sif $pq_fmt $name_v) )
+
+    if [[ -z $pkgData ]] ; then
+        pkgData=( $(package-query -Sf $pq_fmt --query-type provides $name) )
+
+        if [[ $#pkgData -ne 4 ]] ; then
+            if [[ $#pkgData -lt 4 ]] ; then
+                # TODO: check aur
+                error "could not find package $name_v"
+            else
+                error "multiple packages provide $name_v"
+                for ignore repo pr_name ver in "${(@)pkgData}" ; do
+                    error "    $pr_name-$ver in $repo"
+                done
+                error "please install one of these and run this script again"
+            fi
+            return 1
+        fi
+    fi
+
+    # check if package conflicts with anything already installed
+    local conflict
+    conflict=( $(package-query -Qf $pq_fmt --query-type conflicts "$pkgData[3]=$pkgData[4]") )
+    if [[ -n $conflict ]] ; then
+        echo "$conflict"
+    else
+        echo "$pkgData"
+    fi
+}
+
 
 collect_pkg_data() {
     local name=$1
@@ -170,62 +210,35 @@ collect_pkg_data() {
                 die "rsync connection died, could not retrieve $basename"
        fi
 
-        typeset -a make_deps
-        make_deps=( $(bash -c 'source /etc/makepkg.conf; source PKGBUILD && echo ${makedepends[@]}') )
+        typeset -a mk_deps
+        mk_deps=( $(bash -c 'source /etc/makepkg.conf; source PKGBUILD && echo ${makedepends[@]}') )
 
-        if [[ $#make_deps > 0 ]] ; then
+        if [[ $#mk_deps > 0 ]] ; then
             verbose "begin dependencies of $name"
-            for dep in $make_deps ; do
-                collect_pkg $dep
-            done
+            if [[ $+make_deps -eq 1 ]] ; then
+                for dep in $mk_deps ; do
+                    collect_pkg $dep
+                done
+            else
+                typeset -a pkgData
+                for dep in $mk_deps ; do
+                    # TODO: store versions with mk_deps
+                    pkgData=( $(resolve_name $dep $dep) )
+                    if [[ $? -eq 0 ]] && ! pacman &>/dev/null -Q $pkgData[3] ; then
+                        makedep_pkgs[$pkgData[3]]=1
+                    fi
+                done
+            fi
             verbose "end dependencies of $name"
         fi
 
-        install_list+=$basename
+        install_pkgs+=$basename
         popd
     fi
 }
 
 as_root() {
     if [[ $UID -eq 0 ]] ; then $* ; else sudo $* ; fi
-}
-
-resolve_name() {
-    local name=$1
-    local name_v=$2
-
-    local pq_fmt="%1 %s %n %v"
-    typeset -a pkgData
-    pkgData=( $(package-query -Qf $pq_fmt --query-type provides $name_v || \
-                package-query -Qif $pq_fmt $name_v || \
-                package-query -Sif $pq_fmt $name_v) )
-
-    if [[ -z $pkgData ]] ; then
-        pkgData=( $(package-query -Sf $pq_fmt --query-type provides $name) )
-
-        if [[ $#pkgData -ne 4 ]] ; then
-            if [[ $#pkgData -lt 4 ]] ; then
-                # TODO: check aur
-                error "could not find package $name_v"
-            else
-                error "multiple packages provide $name_v"
-                for ignore repo pr_name ver in "${(@)pkgData}" ; do
-                    error "    $pr_name-$ver in $repo"
-                done
-                error "please install one of these and run this script again"
-            fi
-            return 1
-        fi
-    fi
-
-    # check if package conflicts with anything already installed
-    local conflict
-    conflict=( $(package-query -Qf $pq_fmt --query-type conflicts "$pkgData[3]=$pkgData[4]") )
-    if [[ -n $conflict ]] ; then
-        echo "$conflict"
-    else
-        echo "$pkgData"
-    fi
 }
 
 processing_pkg() {
@@ -282,7 +295,7 @@ build_pkgs() {
             "could not get binary package for recursive dependency $pkg"
     done
 
-    if [[ $#install_list -eq 0 ]] ; then
+    if [[ $#install_pkgs -eq 0 ]] ; then
         log_info "nothing to install"
         return 0
     fi
@@ -295,7 +308,7 @@ build_pkgs() {
         fi
     fi
 
-    for pkg in "${(@)install_list}" ; do
+    for pkg in "${(@)install_pkgs}" ; do
         build_pkg $pkg
     done
 }
@@ -334,9 +347,10 @@ main() {
         keep-going,k   "do not stop on error" \
         verbose,v      "increase verbosity" \
         quiet,q        "hide output of compilation" \
-        keep-temp,T    "keep temporary files" \
+        keep-build,b   "keep temporary build files" \
         no-abs,A       "do not use local abs mirror (slower)" \
         uncompiled,u   "list packages which have not been custom compiled" \
+        make-deps,m    "compile make dependencies rather than using binaries" \
         compiled,c     "list packages which have been custom compiled" \
         list,l         "list installed packages with their compilation status" \
         -- $*
@@ -358,13 +372,23 @@ main() {
         info "please wait, collecting packages to build"
         collect_pkgs $positionals
 
-        echo "pacmoon install list:"
-        for pkg in $cyclic_deps ; do
-            info $pkg "(as binary due to cyclic dependency)"
-        done
+        if [[ $#cyclic_deps > 0 ]] ; then
+            echo "binaries installed due to cyclic dependencies:"
+            for pkg in $cyclic_deps ; do
+                info $pkg
+            done
+        fi
 
+        if [[ $#makedep_pkgs > 0 ]] ; then
+            echo "binaries installed due to make dependencies:"
+            for pkg in ${(k)makedep_pkgs} ; do
+                info $pkg
+            done
+        fi
+
+        echo "pacmoon install list:"
         local sfx
-        for pkg in "${(@)install_list}" ; do
+        for pkg in "${(@)install_pkgs}" ; do
             sfx=
             is_dep $pkg && sfx="(dependency)"
             info $pkg ${split_pkgs[$pkg]:+"($split_pkgs[$pkg])"} $sfx
